import fs from "node:fs";
import path from "node:path";
import { repoPath } from "./paths";
import { buildDiff, hashContent } from "./diff";
import * as T from "./templates";
import type { DiffResult, FieldSchema } from "@/types";

export type ManagedFileDef = {
  key: string;
  label: string;
  relPaths: string[];
  /** Personal/local files (e.g. .env) never get the "already customized" three-way-diff
   * treatment — there's no meaningful "shipped baseline" to compare a dev's own .env against. */
  personal?: boolean;
  fields: FieldSchema[];
  baseline: (relPath: string) => string;
  parseCurrentValues: () => Record<string, unknown>;
  buildProposed: (values: Record<string, unknown>) => Record<string, string>;
};

function readIfExists(relPath: string): string | null {
  const abs = repoPath(relPath);
  return fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
}

// ── CODEOWNERS ──────────────────────────────────────────────────────────────

type OwnerRow = { pattern: string; owners: string };

function parseCodeowners(content: string): OwnerRow[] {
  return content
    .split("\n")
    .filter((line) => line.trim() && !line.trim().startsWith("#"))
    .map((line) => {
      const [pattern, ...rest] = line.trim().split(/\s+/);
      return { pattern: pattern ?? "", owners: rest.join(" ") };
    })
    .filter((row) => row.pattern);
}

const codeowners: ManagedFileDef = {
  key: "codeowners",
  label: "CODEOWNERS",
  relPaths: ["CODEOWNERS"],
  fields: [
    {
      name: "rows",
      label: "Path → owner rules (evaluated in order, last match wins)",
      type: "table",
      columns: [
        { name: "pattern", label: "Path glob", placeholder: "/scripts/" },
        { name: "owners", label: "Owner(s)", placeholder: "@your-org/platform-maintainers" },
      ],
    },
  ],
  baseline: () => T.CODEOWNERS_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists("CODEOWNERS") ?? "";
    return { rows: parseCodeowners(current) };
  },
  buildProposed: (values) => {
    const rows = (values.rows as OwnerRow[] | undefined) ?? [];
    const header = [
      "# CODEOWNERS — generated by onboarding-ui. Rules are evaluated in order; the last",
      "# matching rule wins.",
      "",
    ].join("\n");
    const body = rows
      .filter((r) => r.pattern?.trim())
      .map((r) => `${r.pattern.padEnd(28)} ${r.owners}`.trimEnd())
      .join("\n");
    return { CODEOWNERS: header + body + "\n" };
  },
};

// ── .pre-commit-config.yaml ─────────────────────────────────────────────────

const preCommitConfig: ManagedFileDef = {
  key: "pre-commit-config",
  label: "Pre-commit hook file globs",
  relPaths: [".pre-commit-config.yaml"],
  fields: [
    { name: "serviceDir", label: "Core service directory name (under codebase/)", type: "text", placeholder: "billing-service" },
    { name: "workersGlob", label: "Workers/lambdas glob (under codebase/)", type: "text", placeholder: "workers/.*" },
    { name: "iacPrefix", label: "IaC repo directory prefix (under codebase/) — leave blank if you have no IaC repo", type: "text", placeholder: "infra" },
  ],
  baseline: () => T.PRE_COMMIT_CONFIG_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists(".pre-commit-config.yaml") ?? T.PRE_COMMIT_CONFIG_BASELINE;
    const serviceDir = /files: \^codebase\/\(([^/]+)\/service\|/.exec(current)?.[1] ?? "";
    const workersGlob = /\/service\|([^)]+)\)\//.exec(current)?.[1] ?? "";
    const iacPrefix = /files: \^codebase\/([^\n]+)$/m.exec(current)?.[1] ?? "";
    return { serviceDir, workersGlob, iacPrefix };
  },
  buildProposed: (values) => {
    const serviceDir = String(values.serviceDir ?? "<service>").trim() || "<service>";
    const workersGlob = String(values.workersGlob ?? "<lambdas-or-workers>").trim() || "<lambdas-or-workers>";
    const iacPrefix = String(values.iacPrefix ?? "").trim();

    let proposed = T.PRE_COMMIT_CONFIG_BASELINE.replaceAll("<service>", serviceDir).replaceAll(
      "<lambdas-or-workers>",
      workersGlob,
    );

    if (iacPrefix) {
      proposed = proposed.replaceAll("<iac-repo-prefix>", iacPrefix);
    } else {
      // No IaC repo — drop the Terraform hook block entirely rather than leave an unmatched
      // placeholder glob in the file.
      proposed = proposed.replace(
        /\n {2}# ── Terraform[\s\S]*?(?=\n {2}# ── General hygiene)/,
        "\n",
      );
    }
    return { ".pre-commit-config.yaml": proposed };
  },
};

// ── .github/workflows/ci.yml ────────────────────────────────────────────────

const ciWorkflow: ManagedFileDef = {
  key: "ci-workflow",
  label: "CI lint/test steps",
  relPaths: [".github/workflows/ci.yml"],
  fields: [
    { name: "lintSteps", label: "Lint job steps (YAML, inserted after checkout)", type: "textarea", placeholder: "- uses: actions/setup-python@v5\n  with:\n    python-version: \"3.12\"\n- run: pip install -r requirements.txt\n- run: ruff check ." },
    { name: "testSteps", label: "Test job steps (YAML, inserted after checkout)", type: "textarea", placeholder: "- uses: actions/setup-node@v4\n  with:\n    node-version: \"20\"\n- run: npm ci && npm test" },
  ],
  baseline: () => T.CI_WORKFLOW_BASELINE,
  parseCurrentValues: () => ({ lintSteps: "", testSteps: "" }),
  buildProposed: (values) => {
    const indent = (yaml: string, spaces: number) =>
      yaml
        .split("\n")
        .map((line) => (line.trim() ? " ".repeat(spaces) + line : line))
        .join("\n");

    const lintSteps = String(values.lintSteps ?? "").trim();
    const testSteps = String(values.testSteps ?? "").trim();

    let proposed = T.CI_WORKFLOW_BASELINE;
    if (lintSteps) {
      proposed = proposed.replace(
        /(lint:\n {4}runs-on: ubuntu-latest\n {4}steps:\n {6}- uses: actions\/checkout@v4\n)[\s\S]*?(\n\n {2}test:)/,
        `$1${indent(lintSteps, 6)}\n$2`,
      );
    }
    if (testSteps) {
      proposed = proposed.replace(
        /(test:\n {4}runs-on: ubuntu-latest\n {4}steps:\n {6}- uses: actions\/checkout@v4\n)[\s\S]*?(\n\n {2}pre-commit:)/,
        `$1${indent(testSteps, 6)}\n$2`,
      );
    }
    return { ".github/workflows/ci.yml": proposed };
  },
};

// ── .github/instructions/global.instructions.md (Sensor Dispatch Table only) ─

type SensorRow = { pattern: string; command: string; cwd: string };
const ANCHOR_START = "<!-- sensor-dispatch-table:start -->";
const ANCHOR_END = "<!-- sensor-dispatch-table:end -->";

function parseSensorTable(content: string): SensorRow[] {
  const start = content.indexOf(ANCHOR_START);
  const end = content.indexOf(ANCHOR_END);
  if (start === -1 || end === -1) return [];
  const block = content.slice(start + ANCHOR_START.length, end).trim();
  const lines = block.split("\n").filter((l) => l.trim().startsWith("|"));
  return lines
    .slice(2) // header + separator
    .map((line) => {
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((c) => c.trim());
      return { pattern: cells[0] ?? "", command: cells[1] ?? "", cwd: cells[2] ?? "" };
    })
    .filter((r) => r.pattern);
}

function renderSensorTable(rows: SensorRow[]): string {
  const header = "| File Pattern | Sensor Command | Cwd |\n|---|---|---|\n";
  return header + rows.map((r) => `| ${r.pattern} | ${r.command} | ${r.cwd} |`).join("\n") + "\n";
}

const globalInstructions: ManagedFileDef = {
  key: "global-instructions",
  label: "Sensor Dispatch Table",
  relPaths: [".github/instructions/global.instructions.md"],
  fields: [
    {
      name: "rows",
      label: "File pattern → sensor command → cwd",
      type: "table",
      columns: [
        { name: "pattern", label: "File pattern", placeholder: "codebase/billing-service/src/**/*.py" },
        { name: "command", label: "Sensor command", placeholder: "ruff check {file} && pytest -xvs tests/" },
        { name: "cwd", label: "Cwd", placeholder: "codebase/billing-service/" },
      ],
    },
  ],
  baseline: () => T.GLOBAL_INSTRUCTIONS_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists(".github/instructions/global.instructions.md") ?? T.GLOBAL_INSTRUCTIONS_BASELINE;
    return { rows: parseSensorTable(current) };
  },
  buildProposed: (values) => {
    const rows = (values.rows as SensorRow[] | undefined) ?? [];
    const current = readIfExists(".github/instructions/global.instructions.md") ?? T.GLOBAL_INSTRUCTIONS_BASELINE;
    const start = current.indexOf(ANCHOR_START);
    const end = current.indexOf(ANCHOR_END);
    if (start === -1 || end === -1) {
      throw new Error(
        "global.instructions.md is missing the sensor-dispatch-table anchors — cannot safely regenerate the table.",
      );
    }
    const before = current.slice(0, start + ANCHOR_START.length);
    const after = current.slice(end);
    const proposed = `${before}\n${renderSensorTable(rows)}${after}`;
    return { ".github/instructions/global.instructions.md": proposed };
  },
};

// ── config/repos.json ───────────────────────────────────────────────────────

type ReposDoc = {
  github: { org: string; protocol: "ssh" | "https" };
  groups: Record<string, string>;
  repos: Array<{ name: string; tier: "core" | "worker"; group?: string }>;
};

const reposJson: ManagedFileDef = {
  key: "repos-json",
  label: "config/repos.json",
  relPaths: ["config/repos.json"],
  fields: [], // driven by the custom gh-backed repo picker UI, not a generic form
  baseline: () => T.REPOS_JSON_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists("config/repos.json");
    try {
      return current ? JSON.parse(current) : {};
    } catch {
      return {};
    }
  },
  buildProposed: (values) => {
    const doc = values as unknown as ReposDoc;
    return { "config/repos.json": JSON.stringify({ github: doc.github, groups: doc.groups, repos: doc.repos }, null, 2) + "\n" };
  },
};

// ── .env (personal — DEV_EMAIL / AWS_* / START_MODE / JIRA_*) ──────────────

function parseEnvFile(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line);
    if (m) out[m[1]!] = m[2] ?? "";
  }
  return out;
}

function upsertEnvKeys(content: string, updates: Record<string, string>): string {
  const lines = content.split("\n");
  const seen = new Set<string>();
  const next = lines.map((line) => {
    const m = /^([A-Z_][A-Z0-9_]*)=/.exec(line);
    if (m && Object.prototype.hasOwnProperty.call(updates, m[1]!)) {
      seen.add(m[1]!);
      return `${m[1]}=${updates[m[1]!]}`;
    }
    return line;
  });
  const missing = Object.entries(updates).filter(([k]) => !seen.has(k));
  if (missing.length > 0) {
    if (next[next.length - 1]?.trim() !== "") next.push("");
    next.push("# ── Added by onboarding-ui ──");
    for (const [k, v] of missing) next.push(`${k}=${v}`);
  }
  return next.join("\n").replace(/\n{3,}/g, "\n\n");
}

const envFile: ManagedFileDef = {
  key: "env",
  label: ".env",
  relPaths: [".env"],
  personal: true,
  fields: [
    { name: "DEV_EMAIL", label: "Your work email", type: "text", placeholder: "you@your-company.com" },
    { name: "AWS_ENV", label: "AWS environment", type: "text", placeholder: "dev" },
    { name: "AWS_PROFILE", label: "AWS CLI profile name", type: "text", placeholder: "your-profile" },
    { name: "JIRA_BASE_URL", label: "Jira base URL", type: "text", placeholder: "https://your-org.atlassian.net" },
    { name: "JIRA_API_TOKEN", label: "Jira API token", type: "text", placeholder: "atlassian API token" },
  ],
  baseline: () => T.ENV_TEMPLATE_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists(".env") ?? readIfExists(".env.template") ?? T.ENV_TEMPLATE_BASELINE;
    return parseEnvFile(current);
  },
  buildProposed: (values) => {
    const current = readIfExists(".env") ?? readIfExists(".env.template") ?? T.ENV_TEMPLATE_BASELINE;
    const updates: Record<string, string> = {};
    for (const [k, v] of Object.entries(values)) updates[k] = String(v ?? "");
    return { ".env": upsertEnvKeys(current, updates) };
  },
};

// ── .env.template (bootstraps .env for scripts/profile.sh) ─────────────────

const envTemplateFile: ManagedFileDef = {
  key: "env-template",
  label: ".env.template",
  relPaths: [".env.template"],
  fields: [],
  baseline: () => T.ENV_TEMPLATE_BASELINE,
  parseCurrentValues: () => ({}),
  buildProposed: () => ({ ".env.template": T.ENV_TEMPLATE_BASELINE }),
};

// ── jira_client board/project constants ─────────────────────────────────────

const jiraBoard: ManagedFileDef = {
  key: "jira-board",
  label: "Jira board/project constants",
  relPaths: ["jira_client/fetch_my_stories.py", "jira_client/fetch_sprint_stories.py"],
  fields: [
    { name: "boardId", label: "Jira board ID", type: "text", placeholder: "42" },
    { name: "projectKey", label: "Jira project key", type: "text", placeholder: "PROJ" },
  ],
  baseline: (relPath) => {
    // Only the two constant lines matter for diffing; read-through for the rest.
    return readIfExists(relPath) ?? "";
  },
  parseCurrentValues: () => {
    const my = readIfExists("jira_client/fetch_my_stories.py") ?? "";
    const sprint = readIfExists("jira_client/fetch_sprint_stories.py") ?? "";
    const boardId = /BOARD_ID = (\d+)/.exec(my)?.[1] ?? /BOARD_ID = (\d+)/.exec(sprint)?.[1] ?? "0";
    const projectKey = /PROJECT = "([^"]*)"/.exec(my)?.[1] ?? "PROJ";
    return { boardId, projectKey };
  },
  buildProposed: (values) => {
    const boardId = String(values.boardId ?? "0").trim() || "0";
    const projectKey = String(values.projectKey ?? "PROJ").trim() || "PROJ";
    const my = readIfExists("jira_client/fetch_my_stories.py") ?? "";
    const sprint = readIfExists("jira_client/fetch_sprint_stories.py") ?? "";
    const myProposed = my
      .replace(/BOARD_ID = \d+.*/, `BOARD_ID = ${boardId}`)
      .replace(/PROJECT = "[^"]*".*/, `PROJECT = "${projectKey}"`);
    const sprintProposed = sprint.replace(/BOARD_ID = \d+.*/, `BOARD_ID = ${boardId}`);
    return {
      "jira_client/fetch_my_stories.py": myProposed,
      "jira_client/fetch_sprint_stories.py": sprintProposed,
    };
  },
};

const REGISTRY: Record<string, ManagedFileDef> = {
  codeowners,
  "pre-commit-config": preCommitConfig,
  "ci-workflow": ciWorkflow,
  "global-instructions": globalInstructions,
  "repos-json": reposJson,
  env: envFile,
  "env-template": envTemplateFile,
  "jira-board": jiraBoard,
};

export function getManagedFile(key: string): ManagedFileDef | undefined {
  return REGISTRY[key];
}

export function listManagedFileKeys(): string[] {
  return Object.keys(REGISTRY);
}

export function diffManagedFile(key: string, values: Record<string, unknown>): DiffResult[] {
  const def = getManagedFile(key);
  if (!def) throw new Error(`Unknown managed file "${key}"`);
  const proposedMap = def.buildProposed(values);
  return def.relPaths.map((relPath) => {
    const absolute = repoPath(relPath);
    const result = buildDiff({
      key: `${key}:${relPath}`,
      absolutePath: absolute,
      baseline: def.baseline(relPath),
      proposed: proposedMap[relPath] ?? "",
    });
    // A personal file (like .env) is never "customized" relative to a shipped baseline — every
    // dev's .env differs from every other dev's by design.
    if (def.personal) result.customized = false;
    return result;
  });
}

export function writeManagedFile(
  key: string,
  values: Record<string, unknown>,
  confirmedHashes: Record<string, string>,
  force: boolean,
): { relPath: string; ok: boolean; backupPath?: string; reason?: string }[] {
  const def = getManagedFile(key);
  if (!def) throw new Error(`Unknown managed file "${key}"`);
  const proposedMap = def.buildProposed(values);

  return def.relPaths.map((relPath) => {
    const absolute = repoPath(relPath);
    const existsNow = fs.existsSync(absolute);
    const currentNow = existsNow ? fs.readFileSync(absolute, "utf8") : "";
    const confirmedHash = confirmedHashes[relPath];

    if (!force && confirmedHash && hashContent(currentNow) !== confirmedHash) {
      return {
        relPath,
        ok: false,
        reason: "File changed on disk since the diff was shown — re-open the diff and try again.",
      };
    }

    let backupPath: string | undefined;
    if (existsNow) {
      backupPath = `${absolute}.bak-${Date.now()}`;
      fs.copyFileSync(absolute, backupPath);
    }

    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    fs.writeFileSync(absolute, proposedMap[relPath] ?? "", "utf8");
    return { relPath, ok: true, backupPath };
  });
}
