import fs from "node:fs";
import path from "node:path";
import { repoPath } from "./paths";
import { buildDiff, hashContent } from "./diff";
import * as T from "./templates";
import type { DiffResult, FieldSchema } from "@/types";

export type ManagedFileDef = {
  key: string;
  label: string;
  relPaths: string[];
  /** Personal/local files (e.g. .env) never get the "already customized" three-way-diff
   * treatment — there's no meaningful "shipped baseline" to compare a dev's own .env against. */
  personal?: boolean;
  fields: FieldSchema[];
  /** Overrides `fields` when present — for schemas whose `options` (dropdown suggestions)
   * depend on runtime state (e.g. the repos configured in config/repos.json) rather than being
   * fixed at module load. */
  getFields?: () => FieldSchema[];
  baseline: (relPath: string) => string;
  parseCurrentValues: () => Record<string, unknown>;
  buildProposed: (values: Record<string, unknown>) => Record<string, string>;
};

function readIfExists(relPath: string): string | null {
  const abs = repoPath(relPath);
  return fs.existsSync(abs) ? fs.readFileSync(abs, "utf8") : null;
}

// ── shared: repos configured in "Configure & clone repos" ───────────────────
// Used to offer real directory names as dropdown suggestions instead of empty text inputs
// (e.g. pre-commit-config's serviceDir/workersGlob/iacPrefix fields below).

type ConfiguredRepo = { name: string; tier: "core" | "worker" };

function readConfiguredRepos(): ConfiguredRepo[] {
  const raw = readIfExists("config/repos.json");
  if (!raw) return [];
  try {
    const doc = JSON.parse(raw) as { repos?: ConfiguredRepo[] };
    // The shipped template ships with placeholder repo entries (e.g. "<service-name>") so
    // scripts/clone-repos.sh --select has something to overwrite — never real repos, so never
    // worth offering as a dropdown suggestion.
    return (doc.repos ?? []).filter((r) => r.name && !/^<[^>]+>$/.test(r.name));
  } catch {
    return [];
  }
}

// ── CODEOWNERS ──────────────────────────────────────────────────────────────

type OwnerRow = { pattern: string; owners: string };

function parseCodeowners(content: string): OwnerRow[] {
  return content
    .split("\n")
    .filter((line) => line.trim() && !line.trim().startsWith("#"))
    .map((line) => {
      const [pattern, ...rest] = line.trim().split(/\s+/);
      return { pattern: pattern ?? "", owners: rest.join(" ") };
    })
    .filter((row) => row.pattern);
}

const codeowners: ManagedFileDef = {
  key: "codeowners",
  label: "CODEOWNERS",
  relPaths: ["CODEOWNERS"],
  fields: [
    {
      name: "rows",
      label: "Path → owner rules (evaluated in order, last match wins)",
      type: "table",
      columns: [
        { name: "pattern", label: "Path glob", placeholder: "/scripts/" },
        { name: "owners", label: "Owner(s)", placeholder: "@your-org/platform-maintainers" },
      ],
    },
  ],
  baseline: () => T.CODEOWNERS_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists("CODEOWNERS") ?? "";
    return { rows: parseCodeowners(current) };
  },
  buildProposed: (values) => {
    const rows = (values.rows as OwnerRow[] | undefined) ?? [];
    const header = [
      "# CODEOWNERS — generated by onboarding-ui. Rules are evaluated in order; the last",
      "# matching rule wins.",
      "",
    ].join("\n");
    const body = rows
      .filter((r) => r.pattern?.trim())
      .map((r) => `${r.pattern.padEnd(28)} ${r.owners}`.trimEnd())
      .join("\n");
    return { CODEOWNERS: header + body + "\n" };
  },
};

// ── .pre-commit-config.yaml ─────────────────────────────────────────────────

/** Reads the directory names already chosen in the Pre-commit step (serviceDir, workersGlob,
 * iacPrefix). Shared with the Sensor Dispatch Table below so a team only ever names its
 * repos once — the sensor table auto-fills from whatever pre-commit already knows instead of
 * asking again. */
function readPreCommitDirValues(): { serviceDir: string; workersGlob: string; iacPrefix: string } {
  const current = readIfExists(".pre-commit-config.yaml") ?? T.PRE_COMMIT_CONFIG_BASELINE;
  const serviceDir = /files: \^codebase\/\(([^/]+)\/service\|/.exec(current)?.[1] ?? "";
  const workersGlob = /\/service\|([^)]+)\)\//.exec(current)?.[1] ?? "";
  const iacPrefix = /id: terraform_fmt\s*\n\s*files: \^codebase\/([^\n]+)/.exec(current)?.[1] ?? "";
  // Still-unfilled placeholder tokens (angle-bracket names) aren't real directory names — treat
  // them the same as "not set yet" rather than showing/reusing literal "<service>" text.
  const clean = (v: string) => (/^<[^>]+>/.test(v) ? "" : v);
  return { serviceDir: clean(serviceDir), workersGlob: clean(workersGlob), iacPrefix: clean(iacPrefix) };
}

const preCommitConfig: ManagedFileDef = {
  key: "pre-commit-config",
  label: "Pre-commit hook file globs",
  relPaths: [".pre-commit-config.yaml"],
  fields: [
    { name: "serviceDir", label: "Core service directory name (under codebase/)", type: "text", placeholder: "billing-service" },
    { name: "workersGlob", label: "Workers/lambdas glob (under codebase/)", type: "text", placeholder: "workers/.*" },
    { name: "iacPrefix", label: "IaC repo directory prefix (under codebase/) — leave blank if you have no IaC repo", type: "text", placeholder: "infra" },
  ],
  // Dropdown suggestions come from config/repos.json (the "Configure & clone repos" step) rather
  // than being fixed at module load, since which repos exist is only known at runtime — the
  // fields themselves stay freeform text inputs so a custom value can still be typed.
  getFields: () => {
    const repos = readConfiguredRepos();
    const coreOptions = repos.filter((r) => r.tier === "core").map((r) => ({ value: r.name, label: r.name }));
    const workerRepos = repos.filter((r) => r.tier === "worker");
    const workerOptions = [
      ...(workerRepos.length > 1 ? [{ value: "workers/.*", label: "workers/.* (all worker repos below)" }] : []),
      ...workerRepos.map((r) => ({ value: r.name, label: r.name })),
    ];
    const allOptions = repos.map((r) => ({ value: r.name, label: `${r.name} (${r.tier})` }));
    const pickHelp = repos.length > 0 ? "Pick from your configured repos, or type your own." : undefined;
    return [
      {
        name: "serviceDir",
        label: "Core service directory name (under codebase/)",
        type: "text",
        placeholder: "billing-service",
        options: coreOptions,
        help: coreOptions.length > 0 ? pickHelp : undefined,
      },
      {
        name: "workersGlob",
        label: "Workers/lambdas glob (under codebase/)",
        type: "text",
        placeholder: "workers/.*",
        options: workerOptions,
        help: workerOptions.length > 0 ? pickHelp : undefined,
      },
      {
        name: "iacPrefix",
        label: "IaC repo directory prefix (under codebase/) — leave blank if you have no IaC repo",
        type: "text",
        placeholder: "infra",
        options: allOptions,
        help: allOptions.length > 0 ? pickHelp : undefined,
      },
    ];
  },
  baseline: () => T.PRE_COMMIT_CONFIG_BASELINE,
  parseCurrentValues: () => readPreCommitDirValues(),
  buildProposed: (values) => {
    const serviceDir = String(values.serviceDir ?? "<service>").trim() || "<service>";
    const workersGlob = String(values.workersGlob ?? "<lambdas-or-workers>").trim() || "<lambdas-or-workers>";
    const iacPrefix = String(values.iacPrefix ?? "").trim();

    let proposed = T.PRE_COMMIT_CONFIG_BASELINE.replaceAll("<service>", serviceDir).replaceAll(
      "<lambdas-or-workers>",
      workersGlob,
    );

    if (iacPrefix) {
      proposed = proposed.replaceAll("<iac-repo-prefix>", iacPrefix);
    } else {
      // No IaC repo — drop the Terraform hook block entirely rather than leave an unmatched
      // placeholder glob in the file.
      proposed = proposed.replace(
        /\n {2}# ── Terraform[\s\S]*?(?=\n {2}# ── General hygiene)/,
        "\n",
      );
    }
    return { ".pre-commit-config.yaml": proposed };
  },
};

// ── .github/instructions/global.instructions.md (Sensor Dispatch Table only) ─

type SensorRow = { pattern: string; command: string; cwd: string };
const ANCHOR_START = "<!-- sensor-dispatch-table:start -->";
const ANCHOR_END = "<!-- sensor-dispatch-table:end -->";

function parseSensorTable(content: string): SensorRow[] {
  const start = content.indexOf(ANCHOR_START);
  const end = content.indexOf(ANCHOR_END);
  if (start === -1 || end === -1) return [];
  const block = content.slice(start + ANCHOR_START.length, end).trim();
  const lines = block.split("\n").filter((l) => l.trim().startsWith("|"));
  return lines
    .slice(2) // header + separator
    .map((line) => {
      const cells = line
        .split("|")
        .slice(1, -1)
        .map((c) => c.trim());
      return { pattern: cells[0] ?? "", command: cells[1] ?? "", cwd: cells[2] ?? "" };
    })
    .filter((r) => r.pattern);
}

function renderSensorTable(rows: SensorRow[]): string {
  const header = "| File Pattern | Sensor Command | Cwd |\n|---|---|---|\n";
  return header + rows.map((r) => `| ${r.pattern} | ${r.command} | ${r.cwd} |`).join("\n") + "\n";
}

const globalInstructions: ManagedFileDef = {
  key: "global-instructions",
  label: "Sensor Dispatch Table",
  relPaths: [".github/instructions/global.instructions.md"],
  fields: [
    {
      name: "rows",
      label: "File pattern → sensor command → cwd",
      type: "table",
      columns: [
        { name: "pattern", label: "File pattern", placeholder: "codebase/billing-service/src/**/*.py" },
        { name: "command", label: "Sensor command", placeholder: "ruff check {file} && pytest -xvs tests/", suggestable: true },
        { name: "cwd", label: "Cwd", placeholder: "codebase/billing-service/" },
      ],
    },
  ],
  // Dropdown suggestions for pattern/cwd come from whatever repos are already configured, same
  // pattern as pre-commit-config's getFields — these are just suggestions offered on an empty
  // input, never pre-filled row values.
  getFields: () => {
    const repos = readConfiguredRepos();
    const dirOptions = repos.map((r) => ({
      value: r.tier === "worker" ? `codebase/workers/${r.name}` : `codebase/${r.name}`,
      label: `${r.name} (${r.tier})`,
    }));
    const pickHelp = dirOptions.length > 0 ? "Pattern/cwd columns suggest your configured repo directories — pick one or type your own." : undefined;
    return [
      {
        name: "rows",
        label: "File pattern → sensor command → cwd",
        type: "table",
        help: pickHelp,
        columns: [
          { name: "pattern", label: "File pattern", placeholder: "codebase/billing-service/src/**/*.py", options: dirOptions },
          { name: "command", label: "Sensor command", placeholder: "ruff check {file} && pytest -xvs tests/", suggestable: true },
          { name: "cwd", label: "Cwd", placeholder: "codebase/billing-service/", options: dirOptions },
        ],
      },
    ];
  },
  baseline: () => T.GLOBAL_INSTRUCTIONS_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists(".github/instructions/global.instructions.md");
    // Same "still exactly the shipped placeholder" check detectors.ts uses for this file's
    // status badge — while true, the form starts with an empty table (no pre-filled default
    // rows/values); the placeholder text on each column and the guidance note above the table
    // (sensorGuidanceNote) are the only examples shown. Once the user has written their own
    // rows, those are the source of truth as-is.
    const stillDefault = !current || current.includes("<service>/src/**/*.py");
    if (stillDefault) return { rows: [] };
    return { rows: parseSensorTable(current!) };
  },
  buildProposed: (values) => {
    const rows = (values.rows as SensorRow[] | undefined) ?? [];
    const current = readIfExists(".github/instructions/global.instructions.md") ?? T.GLOBAL_INSTRUCTIONS_BASELINE;
    const start = current.indexOf(ANCHOR_START);
    const end = current.indexOf(ANCHOR_END);
    if (start === -1 || end === -1) {
      throw new Error(
        "global.instructions.md is missing the sensor-dispatch-table anchors — cannot safely regenerate the table.",
      );
    }
    const before = current.slice(0, start + ANCHOR_START.length);
    const after = current.slice(end);
    const proposed = `${before}\n${renderSensorTable(rows)}${after}`;
    return { ".github/instructions/global.instructions.md": proposed };
  },
};

// ── config/repos.json ───────────────────────────────────────────────────────

type ReposDoc = {
  github: { org: string; protocol: "ssh" | "https" };
  repos: Array<{ name: string; tier: "core" | "worker" }>;
};

const reposJson: ManagedFileDef = {
  key: "repos-json",
  label: "config/repos.json",
  relPaths: ["config/repos.json"],
  fields: [], // driven by the custom gh-backed repo picker UI, not a generic form
  baseline: () => T.REPOS_JSON_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists("config/repos.json");
    try {
      return current ? JSON.parse(current) : {};
    } catch {
      return {};
    }
  },
  buildProposed: (values) => {
    const doc = values as unknown as ReposDoc;
    return { "config/repos.json": JSON.stringify({ github: doc.github, repos: doc.repos }, null, 2) + "\n" };
  },
};

// ── .env (personal — DEV_EMAIL / JIRA_*) ────────────────────────────────────

function parseEnvFile(content: string): Record<string, string> {
  const out: Record<string, string> = {};
  for (const line of content.split("\n")) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line);
    if (m) out[m[1]!] = m[2] ?? "";
  }
  return out;
}

function upsertEnvKeys(content: string, updates: Record<string, string>): string {
  const lines = content.split("\n");
  const seen = new Set<string>();
  const next = lines.map((line) => {
    const m = /^([A-Z_][A-Z0-9_]*)=/.exec(line);
    if (m && Object.prototype.hasOwnProperty.call(updates, m[1]!)) {
      seen.add(m[1]!);
      return `${m[1]}=${updates[m[1]!]}`;
    }
    return line;
  });
  const missing = Object.entries(updates).filter(([k]) => !seen.has(k));
  if (missing.length > 0) {
    if (next[next.length - 1]?.trim() !== "") next.push("");
    next.push("# ── Added by onboarding-ui ──");
    for (const [k, v] of missing) next.push(`${k}=${v}`);
  }
  return next.join("\n").replace(/\n{3,}/g, "\n\n");
}

const envFile: ManagedFileDef = {
  key: "env",
  label: ".env",
  relPaths: [".env"],
  personal: true,
  fields: [
    { name: "DEV_EMAIL", label: "Your work email", type: "text", placeholder: "you@your-company.com", help: "Also used as the Jira auth email." },
    { name: "JIRA_BASE_URL", label: "Jira base URL", type: "text", placeholder: "https://your-org.atlassian.net" },
    { name: "JIRA_API_TOKEN", label: "Jira API token", type: "text", placeholder: "atlassian API token" },
  ],
  baseline: () => T.ENV_BASELINE,
  parseCurrentValues: () => {
    const current = readIfExists(".env") ?? T.ENV_BASELINE;
    return parseEnvFile(current);
  },
  buildProposed: (values) => {
    const current = readIfExists(".env") ?? T.ENV_BASELINE;
    const updates: Record<string, string> = {};
    for (const [k, v] of Object.entries(values)) updates[k] = String(v ?? "");
    return { ".env": upsertEnvKeys(current, updates) };
  },
};

// ── atlassian_client board/project constants ────────────────────────────────

const jiraBoard: ManagedFileDef = {
  key: "jira-board",
  label: "Jira board/project constants",
  relPaths: ["atlassian_client/fetch_my_stories.py", "atlassian_client/fetch_sprint_stories.py"],
  fields: [
    { name: "boardId", label: "Jira board ID", type: "text", placeholder: "42" },
    { name: "projectKey", label: "Jira project key", type: "text", placeholder: "PROJ" },
  ],
  baseline: (relPath) => {
    // Only the two constant lines matter for diffing; read-through for the rest.
    return readIfExists(relPath) ?? "";
  },
  parseCurrentValues: () => {
    const my = readIfExists("atlassian_client/fetch_my_stories.py") ?? "";
    const sprint = readIfExists("atlassian_client/fetch_sprint_stories.py") ?? "";
    const boardId = /BOARD_ID = (\d+)/.exec(my)?.[1] ?? /BOARD_ID = (\d+)/.exec(sprint)?.[1] ?? "0";
    const projectKey = /PROJECT = "([^"]*)"/.exec(my)?.[1] ?? "PROJ";
    return { boardId, projectKey };
  },
  buildProposed: (values) => {
    const boardId = String(values.boardId ?? "0").trim() || "0";
    const projectKey = String(values.projectKey ?? "PROJ").trim() || "PROJ";
    const my = readIfExists("atlassian_client/fetch_my_stories.py") ?? "";
    const sprint = readIfExists("atlassian_client/fetch_sprint_stories.py") ?? "";
    const myProposed = my
      .replace(/BOARD_ID = \d+.*/, `BOARD_ID = ${boardId}`)
      .replace(/PROJECT = "[^"]*".*/, `PROJECT = "${projectKey}"`);
    const sprintProposed = sprint.replace(/BOARD_ID = \d+.*/, `BOARD_ID = ${boardId}`);
    return {
      "atlassian_client/fetch_my_stories.py": myProposed,
      "atlassian_client/fetch_sprint_stories.py": sprintProposed,
    };
  },
};

const REGISTRY: Record<string, ManagedFileDef> = {
  codeowners,
  "pre-commit-config": preCommitConfig,
  "global-instructions": globalInstructions,
  "repos-json": reposJson,
  env: envFile,
  "jira-board": jiraBoard,
};

export function getManagedFile(key: string): ManagedFileDef | undefined {
  return REGISTRY[key];
}

export function listManagedFileKeys(): string[] {
  return Object.keys(REGISTRY);
}

export function diffManagedFile(key: string, values: Record<string, unknown>): DiffResult[] {
  const def = getManagedFile(key);
  if (!def) throw new Error(`Unknown managed file "${key}"`);
  const proposedMap = def.buildProposed(values);
  return def.relPaths.map((relPath) => {
    const absolute = repoPath(relPath);
    const result = buildDiff({
      key: `${key}:${relPath}`,
      absolutePath: absolute,
      baseline: def.baseline(relPath),
      proposed: proposedMap[relPath] ?? "",
    });
    // A personal file (like .env) is never "customized" relative to a shipped baseline — every
    // dev's .env differs from every other dev's by design.
    if (def.personal) result.customized = false;
    return result;
  });
}

export function writeManagedFile(
  key: string,
  values: Record<string, unknown>,
  confirmedHashes: Record<string, string>,
  force: boolean,
): { relPath: string; ok: boolean; backupPath?: string; reason?: string }[] {
  const def = getManagedFile(key);
  if (!def) throw new Error(`Unknown managed file "${key}"`);
  const proposedMap = def.buildProposed(values);

  return def.relPaths.map((relPath) => {
    const absolute = repoPath(relPath);
    const existsNow = fs.existsSync(absolute);
    const currentNow = existsNow ? fs.readFileSync(absolute, "utf8") : "";
    const confirmedHash = confirmedHashes[relPath];

    if (!force && confirmedHash && hashContent(currentNow) !== confirmedHash) {
      return {
        relPath,
        ok: false,
        reason: "File changed on disk since the diff was shown — re-open the diff and try again.",
      };
    }

    let backupPath: string | undefined;
    if (existsNow) {
      backupPath = `${absolute}.bak-${Date.now()}`;
      fs.copyFileSync(absolute, backupPath);
    }

    fs.mkdirSync(path.dirname(absolute), { recursive: true });
    fs.writeFileSync(absolute, proposedMap[relPath] ?? "", "utf8");
    return { relPath, ok: true, backupPath };
  });
}
